FROM python

MAINTAINER ilectra "ilektra.christidi@ucl.ac.uk"

RUN git clone https://github.com/UCL/HHyeast-server.git

WORKDIR /HHyeast-server

RUN pip install -r requirements.txt

COPY YLR422W.0.ssw11.hhr /HHyeast-server/

EXPOSE 5006

CMD bokeh serve lolliplotServer.py --allow-websocket-origin={{url}}:5006
